apiVersion: apps/v1
kind: Deployment
metadata:
  name: adityaert
  namespace: default
  labels:
    app: adityaert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adityaert
  template:
    metadata:
      labels:
        app: adityaert
    spec:
      containers:
      - name: adityaert
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/demo/adityaert:latest
---
apiVersion: v1
kind: Service
metadata:
  name: adityaert-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
